"""Protocol-aware, bounded residual memory for materials discovery.

This package is deliberately separate from the document-curation memory stack.
It consumes native structure and calculation outcomes, never LLM annotations.
"""

from .acquisition import (
    AcquisitionScore,
    FrozenHullDistanceAcquisition,
    PosteriorUncertaintyAcquisition,
    SeededRandomAcquisition,
    SurvivalConditionedAcquisition,
)
from .baselines import (
    DiversityBoundedMemory,
    FIFOBoundedMemory,
)
from .calibration_utility import CalibrationUtilityBuilder, CalibrationUtilityMatrix
from .cards import HullSnapshot, MaterialMemoryCard, MaterialQuery, SourceProvenance
from .coreset import (
    CoresetSelection,
    FacilityLocationCoresetPlanner,
    JointPosteriorRiskOneSwapPlanner,
    JointPosteriorRiskSelection,
    ObjectiveFidelityCandidate,
    ObjectiveFidelityDiagnostic,
    StreamingCalibrationCoreset,
    StreamingJointPosteriorRiskCoreset,
    compare_facility_and_joint_objectives,
)
from .hull_engine import CausalHullEngine
from .identity import CanonicalGroupSplit, MaterialIdentity
from .protocols import (
    CompatibilityKind,
    MatchedResidualPair,
    ProtocolCertificate,
    ProtocolCompatibility,
    ProtocolCompatibilityResolver,
    ProtocolTransportMap,
)
from .residual import ResidualCorrection, ResidualCorrector
from .residual_posterior import (
    FixedKernelGPConfig,
    FixedKernelResidualGP,
    ResidualPosterior,
    ResidualPrediction,
)
from .risk import ConformalCalibration, ProtocolRiskController, RiskDecision, ScreeningDecision
from .wbm import (
    DataAuditFinding,
    DataLicenseAuditReport,
    DataLicenseDecision,
    ExternalDataArtifact,
    FrozenPredictionSOAPCache,
    FrozenPredictionSOAPRecord,
    MPCausalHullBuilder,
    MPPhaseRecord,
    SOAPCacheConfig,
    WBMObservableRecord,
    WBMOracleRecord,
    audit_external_data_artifacts,
)
from .wbm_raw import (
    RAW_WBM_EXPECTED_ENTRY_COUNTS,
    RAW_WBM_FILENAMES,
    WBMRawObservableRecord,
    WBMRawOracleOutcome,
    WBMRawOracleVault,
    WBMRawReleaseReport,
    raw_wbm_records_from_payload,
    validate_raw_wbm_release,
)
from .wbm_secure import (
    AppendOnlyWBMEventLog,
    CompositionHullState,
    CorrectedPhaseEntry,
    ExactEmulationAudit,
    PersistentFIFOEvidence,
    PolicyQuery,
    PolicyState,
    PolicySubprocess,
    PolicyWitness,
    ReconstructedFIFOEvidence,
    RevealedObservation,
    SecureWBMRunner,
    StreamingCoresetEvidence,
    WBMActionRecord,
    WBMEvent,
    WBMOracleVault,
    WBMReplayAudit,
    WBMReveal,
    WBMRevealRecord,
    WBMRunResult,
    assert_exact_emulation,
    replay_wbm_event_log,
)

__all__ = [
    "AcquisitionScore",
    "AppendOnlyWBMEventLog",
    "CalibrationUtilityBuilder",
    "CalibrationUtilityMatrix",
    "CausalHullEngine",
    "CompatibilityKind",
    "CompositionHullState",
    "CorrectedPhaseEntry",
    "CanonicalGroupSplit",
    "ConformalCalibration",
    "CoresetSelection",
    "DataAuditFinding",
    "DataLicenseAuditReport",
    "DataLicenseDecision",
    "DiversityBoundedMemory",
    "FIFOBoundedMemory",
    "FacilityLocationCoresetPlanner",
    "FixedKernelGPConfig",
    "FixedKernelResidualGP",
    "FrozenHullDistanceAcquisition",
    "FrozenPredictionSOAPCache",
    "FrozenPredictionSOAPRecord",
    "HullSnapshot",
    "JointPosteriorRiskOneSwapPlanner",
    "JointPosteriorRiskSelection",
    "MatchedResidualPair",
    "MaterialMemoryCard",
    "MaterialIdentity",
    "MaterialQuery",
    "MPCausalHullBuilder",
    "MPPhaseRecord",
    "PosteriorUncertaintyAcquisition",
    "ObjectiveFidelityCandidate",
    "ObjectiveFidelityDiagnostic",
    "ProtocolCertificate",
    "ProtocolCompatibility",
    "ProtocolCompatibilityResolver",
    "ProtocolRiskController",
    "ProtocolTransportMap",
    "PolicyQuery",
    "PolicyState",
    "PolicySubprocess",
    "PolicyWitness",
    "PersistentFIFOEvidence",
    "ReconstructedFIFOEvidence",
    "RevealedObservation",
    "ResidualCorrection",
    "ResidualCorrector",
    "ResidualPosterior",
    "ResidualPrediction",
    "RiskDecision",
    "ScreeningDecision",
    "SeededRandomAcquisition",
    "SourceProvenance",
    "SecureWBMRunner",
    "StreamingCalibrationCoreset",
    "StreamingCoresetEvidence",
    "StreamingJointPosteriorRiskCoreset",
    "SurvivalConditionedAcquisition",
    "SOAPCacheConfig",
    "WBMObservableRecord",
    "WBMActionRecord",
    "WBMEvent",
    "WBMOracleRecord",
    "WBMOracleVault",
    "WBMReplayAudit",
    "WBMReveal",
    "WBMRevealRecord",
    "WBMRunResult",
    "WBMRawObservableRecord",
    "WBMRawOracleOutcome",
    "WBMRawOracleVault",
    "WBMRawReleaseReport",
    "RAW_WBM_EXPECTED_ENTRY_COUNTS",
    "RAW_WBM_FILENAMES",
    "ExactEmulationAudit",
    "ExternalDataArtifact",
    "assert_exact_emulation",
    "audit_external_data_artifacts",
    "compare_facility_and_joint_objectives",
    "replay_wbm_event_log",
    "raw_wbm_records_from_payload",
    "validate_raw_wbm_release",
]
