"""Protocol-aware, bounded residual memory for materials discovery.

This package is deliberately separate from the document-curation memory stack.
It consumes native structure and calculation outcomes, never LLM annotations.
"""

from .acquisition import (
    AcquisitionScore,
    BaseBoundaryAcquisition,
    BoundaryUncertaintyAcquisition,
    LegacyTwoScenarioAcquisition,
    OnDemandKNNArchiveAcquisition,
    PosteriorUncertaintyAcquisition,
    ProtocolAwareBoundaryAcquisition,
    SeededRandomAcquisition,
    SurvivalConditionedAcquisition,
)
from .active import (
    ActiveDiscoveryEvaluator,
    ActiveDiscoveryMetrics,
    ActiveStep,
    CardOracleVault,
)
from .baselines import (
    DeterministicReservoirMemory,
    DiversityBoundedMemory,
    FIFOBoundedMemory,
    FullHistoryMemory,
    ResidualPriorityMemory,
)
from .boundary import (
    BoundaryEstimate,
    BoundaryPotentialValue,
    BoundaryRetentionSelection,
    BoundaryRiskConfig,
    BoundaryRiskPotential,
    BoundaryRiskRetention,
    BoundaryWitness,
    BruteForceRetentionSolver,
)
from .calibration_utility import CalibrationUtilityBuilder, CalibrationUtilityMatrix
from .cards import HullSnapshot, MaterialMemoryCard, MaterialQuery, SourceProvenance
from .coreset import (
    CoresetSelection,
    FacilityLocationCoresetPlanner,
    StreamingCalibrationCoreset,
)
from .economics import MatchedAccessCost, MatchedAccessCostModel, MatchedAccessOperationLedger
from .evaluation import (
    DeploymentStrategy,
    DiscoveryMetrics,
    OnlineDiscoveryEvaluator,
    RiskCoveragePoint,
    ScreeningOutcome,
    risk_coverage_curve,
)
from .hull_engine import CausalHullEngine, SyntheticMinHullEngine
from .identity import CanonicalGroupSplit, MaterialIdentity
from .protocols import (
    CompatibilityKind,
    MatchedResidualPair,
    ProtocolCertificate,
    ProtocolCompatibility,
    ProtocolCompatibilityResolver,
    ProtocolTransportMap,
)
from .residual import ResidualCorrection, ResidualCorrector
from .residual_posterior import (
    FixedKernelGPConfig,
    FixedKernelResidualGP,
    ResidualPosterior,
    ResidualPrediction,
)
from .risk import ConformalCalibration, ProtocolRiskController, RiskDecision, ScreeningDecision
from .wbm import (
    DataAuditFinding,
    DataLicenseAuditReport,
    DataLicenseDecision,
    ExternalDataArtifact,
    FrozenPredictionSOAPCache,
    FrozenPredictionSOAPRecord,
    MPCausalHullBuilder,
    MPPhaseRecord,
    SOAPCacheConfig,
    WBMObservableRecord,
    WBMOracleRecord,
    audit_external_data_artifacts,
)
from .wbm_raw import (
    RAW_WBM_EXPECTED_ENTRY_COUNTS,
    RAW_WBM_FILENAMES,
    WBMRawObservableRecord,
    WBMRawOracleOutcome,
    WBMRawOracleVault,
    WBMRawReleaseReport,
    raw_wbm_records_from_payload,
    validate_raw_wbm_release,
)
from .wbm_secure import (
    AppendOnlyWBMEventLog,
    CompositionHullState,
    CorrectedPhaseEntry,
    ExactEmulationAudit,
    PersistentFIFOEvidence,
    PolicyQuery,
    PolicyState,
    PolicySubprocess,
    PolicyWitness,
    ReconstructedFIFOEvidence,
    RevealedObservation,
    SecureWBMRunner,
    StreamingCoresetEvidence,
    WBMActionRecord,
    WBMEvent,
    WBMOracleVault,
    WBMReplayAudit,
    WBMReveal,
    WBMRevealRecord,
    WBMRunResult,
    assert_exact_emulation,
    replay_wbm_event_log,
)

__all__ = [
    "AcquisitionScore",
    "ActiveDiscoveryEvaluator",
    "ActiveDiscoveryMetrics",
    "ActiveStep",
    "AppendOnlyWBMEventLog",
    "BaseBoundaryAcquisition",
    "BoundaryUncertaintyAcquisition",
    "BruteForceRetentionSolver",
    "BoundaryEstimate",
    "BoundaryPotentialValue",
    "BoundaryRetentionSelection",
    "BoundaryRiskConfig",
    "BoundaryRiskPotential",
    "BoundaryRiskRetention",
    "BoundaryWitness",
    "CalibrationUtilityBuilder",
    "CalibrationUtilityMatrix",
    "CardOracleVault",
    "CausalHullEngine",
    "CompatibilityKind",
    "CompositionHullState",
    "CorrectedPhaseEntry",
    "CanonicalGroupSplit",
    "ConformalCalibration",
    "CoresetSelection",
    "DataAuditFinding",
    "DataLicenseAuditReport",
    "DataLicenseDecision",
    "DeterministicReservoirMemory",
    "DeploymentStrategy",
    "DiscoveryMetrics",
    "DiversityBoundedMemory",
    "FIFOBoundedMemory",
    "FacilityLocationCoresetPlanner",
    "FixedKernelGPConfig",
    "FixedKernelResidualGP",
    "FullHistoryMemory",
    "FrozenPredictionSOAPCache",
    "FrozenPredictionSOAPRecord",
    "HullSnapshot",
    "LegacyTwoScenarioAcquisition",
    "MatchedResidualPair",
    "MaterialMemoryCard",
    "MaterialIdentity",
    "MaterialQuery",
    "MatchedAccessCost",
    "MatchedAccessCostModel",
    "MatchedAccessOperationLedger",
    "MPCausalHullBuilder",
    "MPPhaseRecord",
    "OnlineDiscoveryEvaluator",
    "OnDemandKNNArchiveAcquisition",
    "PosteriorUncertaintyAcquisition",
    "ProtocolCertificate",
    "ProtocolAwareBoundaryAcquisition",
    "ProtocolCompatibility",
    "ProtocolCompatibilityResolver",
    "ProtocolRiskController",
    "ProtocolTransportMap",
    "PolicyQuery",
    "PolicyState",
    "PolicySubprocess",
    "PolicyWitness",
    "PersistentFIFOEvidence",
    "ReconstructedFIFOEvidence",
    "RevealedObservation",
    "ResidualCorrection",
    "ResidualCorrector",
    "ResidualPosterior",
    "ResidualPrediction",
    "ResidualPriorityMemory",
    "RiskCoveragePoint",
    "RiskDecision",
    "ScreeningDecision",
    "ScreeningOutcome",
    "SeededRandomAcquisition",
    "SourceProvenance",
    "SecureWBMRunner",
    "StreamingCalibrationCoreset",
    "StreamingCoresetEvidence",
    "SurvivalConditionedAcquisition",
    "SyntheticMinHullEngine",
    "SOAPCacheConfig",
    "WBMObservableRecord",
    "WBMActionRecord",
    "WBMEvent",
    "WBMOracleRecord",
    "WBMOracleVault",
    "WBMReplayAudit",
    "WBMReveal",
    "WBMRevealRecord",
    "WBMRunResult",
    "WBMRawObservableRecord",
    "WBMRawOracleOutcome",
    "WBMRawOracleVault",
    "WBMRawReleaseReport",
    "RAW_WBM_EXPECTED_ENTRY_COUNTS",
    "RAW_WBM_FILENAMES",
    "ExactEmulationAudit",
    "ExternalDataArtifact",
    "assert_exact_emulation",
    "audit_external_data_artifacts",
    "replay_wbm_event_log",
    "raw_wbm_records_from_payload",
    "risk_coverage_curve",
    "validate_raw_wbm_release",
]
